apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: baaas-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    konghq.com/plugins: oidc-auth
spec:
  ingressClassName: kong
  tls:
  - secretName: baaas-nip-com
    hosts:
    - 20.127.181.57.nip.io
  rules:
  - host: 20.127.181.57.nip.io
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: baaas
            port:
              number: 80
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: your@email.com #please change this/this is an optional, but recommended setting
    privateKeySecretRef:
      name: letsencrypt-prod
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          podTemplate:
            metadata:
              annotations:
                kuma.io/sidecar-injection: 'false' # If ingress is running in Kuma/Kong Mesh, disable sidecar injection
                sidecar.istio.io/inject: 'false' # If using Istio, disable sidecar injection
          class: kong
